/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

import java.sql.Connection
import java.sql.DriverManager
import java.sql.Statement

class App {
    val greeting: String
        get() {
            return "dupa!"
        }
}

fun main() {
    // Replace "mydatabase.db" with the path to your SQLite database file
    val url = "jdbc:sqlite:/app/db/test.db"
    var connection: Connection? = null

    try {
        // Establish a connection to the SQLite database
        connection = DriverManager.getConnection(url)

        // Create a statement object for executing SQL queries
        val statement: Statement = connection.createStatement()

        // Execute a SELECT query to retrieve the first row from the table
        val resultSet = statement.executeQuery("SELECT * FROM hello_world LIMIT 1")

        // Iterate over the result set
        while (resultSet.next()) {
            // Retrieve values from the result set
            val id = resultSet.getInt("id")
            val str1 = resultSet.getString("str1")
            val str2 = resultSet.getString("str2")

            // Display the retrieved values
            println("$str1 $str2")
        }
    } catch (e: Exception) {
        e.printStackTrace()
    } finally {
        // Close the database connection
        try {
            connection?.close()
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}
