# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - super-stronka-na-ebiznes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e140c0d08beb40339210046ea6a9650e }}/kubaq215/ecommerce-app-frontend:${{ github.sha }}
        file: ./ecommerce-app/frontend-zad5_react-app/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'super-stronka-na-ebiznes'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_581aa364e2314bb6bdbc89e7e54ff1d6 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e140c0d08beb40339210046ea6a9650e }}/kubaq215/ecommerce-app-frontend:${{ github.sha }}'
